### ISSUE TITLE
Crashes on macOS 10.14.5

### ISSUE THREAD

**Issue by HankG** [AvaloniaUI/ControlCatalogStandalone#1]
I'm attempting to launch this on macOS and it crashes with the below crash data before rendering the window.  

https://pastebin.com/5uBJRX5b

The steps for reproducing this are a simple checkout, restore, and run which works on Linux:

``` bash
git clone https://github.com/AvaloniaUI/ControlCatalogStandalone.git
cd ControlCatalogStandalone/
dotnet restore
cd ControlCatalog.NetCore/
dotnet run
```

**Comment by kekekeks** [comment]
It needs to be updated to the latest nightly, we've fixed a huge osx issue recently

**Comment by HankG** [comment]
I've blown away my nuget cache and did a new restore/run and it generates the same error as of this morning.

**Comment by HankG** [comment]
Changing to the latest 0.8.1 dependency cibuild0002889 fixed this problem fyi...

**Comment by HankG** [comment]
This is no longer a problem...closing...
